In [ ]:
ls

sample_data/


In [2]:
from google.colab import drive
drive.mount('aiml')

Mounted at aiml


In [3]:
cd/content/aiml/My Drive/Colab Notebooks/

/content/aiml/My Drive/Colab Notebooks


In [4]:
import pandas as pd
import numpy as np
import math
import operator

from sklearn.datasets import load_iris
sk_data = load_iris()
print(sk_data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

#KNN using scikit-learn library

In [5]:
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
iris = datasets.load_iris()
X,y = iris.data[:, :2], iris.target
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 44)
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
knn = neighbors.KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.7631578947368421

#classification report

In [6]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        13
           1       0.60      0.75      0.67        12
           2       0.73      0.62      0.67        13

    accuracy                           0.76        38
   macro avg       0.78      0.76      0.76        38
weighted avg       0.78      0.76      0.77        38



#Normalization

In [7]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
knn = neighbors.KNeighborsClassifier(n_neighbors= 4)
knn.fit(X_train, y_train)
y_pred= knn.predict(X_test)
accuracy_score(y_test, y_pred)

0.6842105263157895

#Confusion matrix

In [8]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[12  1  0]
 [ 1  8  3]
 [ 0  7  6]]


#Adjust rand score

In [9]:
from sklearn.metrics import adjusted_rand_score
adjusted_rand_score(y_test, y_pred)

0.38353825136612024

#Gridsearch

In [10]:
from sklearn.model_selection import GridSearchCV
params = {'n_neighbors':np.arange(1,3), 'metric':['euclidean', 'manhattan']}
grid = GridSearchCV(estimator=knn, param_grid= params)
grid.fit(X_train, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=4, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': array([1, 2])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

#Grid best score and best estimator

In [ ]:
print(grid.best_estimator_.n_neighbors)
print(grid.best_score_)

1
0.7316205533596838


#Randomized parameter optimization

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
params = {'n_neighbors':range(1,5), 'weights':['uniform', 'distance']}
rsearch = RandomizedSearchCV(estimator=knn, param_distributions= params, cv= 4,n_iter=8,random_state=5)
rsearch.fit(X_train, y_train)

RandomizedSearchCV(cv=4, error_score=nan,
                   estimator=KNeighborsClassifier(algorithm='auto',
                                                  leaf_size=30,
                                                  metric='minkowski',
                                                  metric_params=None,
                                                  n_jobs=None, n_neighbors=5,
                                                  p=2, weights='uniform'),
                   iid='deprecated', n_iter=8, n_jobs=None,
                   param_distributions={'n_neighbors': range(1, 5),
                                        'weights': ['uniform', 'distance']},
                   pre_dispatch='2*n_jobs', random_state=5, refit=True,
                   return_train_score=False, scoring=None, verbose=0)

#Best score

In [ ]:
print(rsearch.best_score_)

0.7678571428571428
