In [ ]:
ls

sample_data/


In [ ]:
from google.colab import drive
drive.mount('aiml')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at aiml


In [ ]:
ls

aiml/  sample_data/


In [ ]:
pwd

'/content'

In [ ]:
cd/content/aiml/My Drive/Colab Notebooks

[Errno 2] No such file or directory: '/content/aiml/My Drive/Colab Notebooks'
/content


#3*3 matrix ranging from 2 to 10 values

In [ ]:
import numpy as np
a = np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


#2D arrray with 1 around corners and 0 inside 

In [ ]:
import numpy as np
A = np.ones((4,4))
print('original array')
print(A)
print('with 1 corners and 0 inside')
A[1:-1, 1:-1] = 0
print(A)

original array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
with 1 corners and 0 inside
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#using step on 8*8 matrix

In [ ]:
import numpy as np
A = np.zeros((8,8))
print('original array')
print(A)
print('step on 8*8 matrix')
A[1::2, ::2] = 1
A[ ::2, 1::2] = 1
print(A)

original array
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
step on 8*8 matrix
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#to extract first and second element of 4x4 matrix

In [ ]:
import numpy as np
x = np.arange(0,16).reshape((4,4))
print('original matrix')
print(x)
print('first and second element of 4x4', x[0:2,0:2])


original matrix
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
first and second element of 4x4 [[0 1]
 [4 5]]


#Determinent of array

In [ ]:
import numpy as np
y = np.array([[1,2],[3,4]])
print('matrix is', y)
result = np.linalg.det(y)
print('det of matrix y is', result)

matrix is [[1 2]
 [3 4]]
det of matrix y is -2.0000000000000004


#eigen values and eigen vectors of matrix

In [ ]:
import numpy as np
m = np.mat('3 -2; 1 0')
print('original matrix :')
print(m)
w , v = np.linalg.eigvals(m)
print('eigen values of matrix', w)
print('eigen vectors of matrix', v)
print(w,v)

original matrix :
[[ 3 -2]
 [ 1  0]]
eigen values of matrix 2.0
eigen vectors of matrix 1.0
2.0 1.0


#To normalize 3x3 Random matrix

In [ ]:
import numpy as np
x = np.random.random((3,3))
print('original matrix')
print(x)
xmax , xmin = x.max() , x.min()
x = (x - xmin)/(xmax - xmin)
print('normalization matrix')
print(x)

original matrix
[[0.67216411 0.263023   0.09309086]
 [0.88214402 0.20820121 0.57858855]
 [0.43899529 0.21583217 0.45793765]]
normalization matrix
[[0.73388369 0.21536209 0.        ]
 [1.         0.14588414 0.61529148]
 [0.43837911 0.15555518 0.46238556]]


#To check whether the element start with 'p' or not ?

In [ ]:
import numpy as np
x1 = np.array(['Python', 'PHP', 'Java', 'C++'], dtype = np.str)
print('original array')
print(x1)
x2 = np.char.startswith(x1, "P")
print('element that starts with p is true or false')
print(x2)

original array
['Python' 'PHP' 'Java' 'C++']
element that starts with p is true or false
[ True  True False False]


#Replacing PHP with PYTHON 

In [ ]:
import numpy as np 
n = np.array(['PHP', 'Java', 'C++'], dtype = np.str)
print('original array')
print(n)
m = np.char.replace(n, 'PHP', 'PYHTON')
print('replacing PHP with Python')
print(m)

original array
['PHP' 'Java' 'C++']
replacing PHP with Python
['PYHTON' 'Java' 'C++']


#To get the date and time of yesterday today and tomorrow

In [ ]:
import numpy as np
yesterday = np.datetime64('today', 'D')
print('yesterday:', yesterday)
today = np.datetime64('today', 'D')
print('Today:', today)
tomorrow = np.datetime64('today', 'D')
print('tomorrow', tomorrow)


yesterday: 2020-06-14
Today: 2020-06-14
tomorrow 2020-06-14


#Sort the elements of the given array

In [ ]:
import numpy as np
student_id = np.array([1024, 4300, 1023, 4500])
print('without sorted', student_id)
student_id1 = np.argsort(student_id)
print('with sorted', student_id1)

without sorted [1024 4300 1023 4500]
with sorted [2 0 1 3]
